### ISSUE TITLE
avoid expected exceptions being logged as error instead of debug (coming with Spring 4.1.1)

### ISSUE THREAD

**Issue by skreiker** [zyro23/grails-spring-websocket#15]
I am using a sockjs with the grails-spring-websocket plugin.
I can successfully open a web-socket and send messages with the client. But each time the user navigates away from the page my grails application displays the following error message:
ERROR LoggingWebSocketHandlerDecorator - Transport error for SockJS session id=rn3z3tbc
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
	... 3 more
Caused by: java.io.IOException: Broken pipe

**Comment by zyro23** [comment]
2.0.0M1 working with grails-3.0.0.m2 has been published to bintray. spring version is 4.1.5 so this issue should be fixed. grails-2.4.x will not benefit from that because it is locked to the spring-4.0.x line.
